import type { RunResult } from '../core/types.js';
import { buildReportModel } from './report-model.js';
import { formatCost, formatDuration, formatPercent, formatScore, medal } from './format.js';

const FOOTER = '*Generated by hoodstrut v0.1.0*';

function emptyReport(generatedAt: string): string {
  return `# 🏆 Hoodstrut Benchmark Report

_Generated ${generatedAt}_

No results found.

---
${FOOTER}
`;
}

/**
 * The persisted report (`report.md`). Matrix-first: the score grid is the
 * headline, everything is ranked by score, and the winning profile is called
 * out up top. Emphasis uses bold + emoji so it renders in GitHub/VS Code
 * (markdown can't carry terminal color — that lives in the CLI output).
 */
export function generateAggregateReport(results: RunResult[], generatedAt: string): string {
  if (results.length === 0) {
    return emptyReport(generatedAt);
  }

  const model = buildReportModel(results);
  const { aggregate, profiles, tasks, matrix, profileTotals, rankedRuns, winner } = model;
  const lines: string[] = [];

  lines.push('# 🏆 Hoodstrut Benchmark Report');
  lines.push('');

  // Winner callout — the single most important takeaway.
  if (winner && profiles.length > 1) {
    lines.push(
      `> **🥇 Winner: \`${winner.name}\`** — ${formatScore(winner.totalScore)} pts ` +
      `across ${winner.runs} run(s) · ${winner.successful}/${winner.runs} passed · ` +
      `${formatCost(winner.totalCost)} total`
    );
    lines.push('');
  }

  lines.push(
    `_Generated ${generatedAt} · ${aggregate.totalRuns} runs · ` +
    `${profiles.length} profile(s) × ${tasks.length} task(s)_`
  );
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Total Runs | ${aggregate.totalRuns} |`);
  lines.push(`| Passed | ${aggregate.successfulRuns} / ${aggregate.totalRuns} (${formatPercent(aggregate.successRate)}) |`);
  lines.push(`| Total Cost | ${formatCost(aggregate.totalCost)} |`);
  lines.push(`| Total Duration | ${formatDuration(aggregate.totalDuration)} |`);
  lines.push(`| Total Score | ${formatScore(aggregate.totalScore)} |`);
  lines.push(`| Avg Score / Run | ${formatScore(aggregate.avgScore)} |`);
  lines.push('');

  // Score Matrix — the centerpiece.
  lines.push('## 📊 Score Matrix');
  lines.push('');
  lines.push('Rows = tasks, columns = profiles, both **ranked by score** (best first). Each cell is the run\'s score; **bold** = best profile for that task, ✅/❌ = pass/fail.');
  lines.push('');

  const header = ['Task', ...profiles.map(p => `${medal(p.rank)} ${p.name}`.trim())];
  const aligns = ['left', ...profiles.map(() => 'right')];
  lines.push(`| ${header.join(' | ')} |`);
  lines.push(`|${aligns.map(a => (a === 'right' ? '---:' : ':---')).join('|')}|`);

  for (const task of tasks) {
    const row = matrix.get(task.id)!;
    const cells = profiles.map(p => {
      const cell = row.get(p.name)!;
      if (!cell.hasRun) return '—';
      const mark = cell.success ? '✅' : '❌';
      const scoreText = formatScore(cell.score);
      return cell.isBestInRow ? `**${scoreText}** ${mark}` : `${scoreText} ${mark}`;
    });
    lines.push(`| **${task.id}** | ${cells.join(' | ')} |`);
  }

  // Column totals footer.
  const totalCells = profiles.map(p => `**${formatScore(profileTotals.get(p.name) ?? 0)}**`);
  lines.push(`| **Total** | ${totalCells.join(' | ')} |`);
  lines.push('');

  // Profile Leaderboard
  lines.push('## 🏅 Profile Leaderboard');
  lines.push('');
  lines.push('| Rank | Profile | Score | Avg / Run | Passed | Cost |');
  lines.push('|-----:|---------|------:|----------:|:------:|-----:|');
  for (const p of profiles) {
    const rankLabel = `${medal(p.rank)} ${p.rank}`.trim();
    lines.push(
      `| ${rankLabel} | \`${p.name}\` | ${formatScore(p.totalScore)} | ${formatScore(p.avgScore)} | ` +
      `${p.successful}/${p.runs} (${formatPercent(p.successRate)}) | ${formatCost(p.totalCost)} |`
    );
  }
  lines.push('');

  // Every run, ranked by score.
  lines.push('## All Runs');
  lines.push('');
  lines.push('Ranked by score (highest first).');
  lines.push('');
  lines.push('| # | Task | Profile | Result | Score | Cost | Time |');
  lines.push('|--:|------|---------|:------:|------:|-----:|-----:|');
  for (const run of rankedRuns) {
    const result = run.success ? '✅' : '❌';
    const cost = run.cost !== null ? formatCost(run.cost) : '—';
    const time = run.duration !== null ? formatDuration(run.duration) : '—';
    lines.push(
      `| ${run.rank} | ${run.taskId} | \`${run.profile}\` | ${result} | ` +
      `${formatScore(run.score)} | ${cost} | ${time} |`
    );
  }
  lines.push('');

  lines.push('---');
  lines.push(FOOTER);

  return lines.join('\n');
}
