import type { BenchmarkAnalysis, ConfidenceInterval, RunResult } from '../core/types.js';
import { buildReportModel } from './report-model.js';
import { formatCost, formatDuration, formatPercent } from './format.js';

const FOOTER = '*Generated by hoodstrut v0.1.0 using lexicographic-v2 methodology*';

function formatInterval(interval: ConfidenceInterval | null, percent = false): string {
  if (interval === null) return 'unavailable';
  if (percent) return `${formatPercent(interval.lower)}-${formatPercent(interval.upper)}`;
  return `${interval.lower.toFixed(3)}-${interval.upper.toFixed(3)}`;
}

function formatContinuousInterval(
  interval: ConfidenceInterval | null,
  formatter: (value: number) => string
): string {
  return interval === null ? 'unavailable' : `${formatter(interval.lower)}-${formatter(interval.upper)}`;
}

function decisionLabel(analysis: BenchmarkAnalysis): string {
  const { decision } = analysis;
  if (decision.winner) return `Winner: \`${decision.winner}\``;
  if (decision.leader) return `Provisional leader: \`${decision.leader}\``;
  return 'No eligible leader';
}

export function generateAggregateReport(
  results: RunResult[],
  generatedAt: string,
  persistedAnalysis?: BenchmarkAnalysis
): string {
  if (results.length === 0 && persistedAnalysis === undefined) {
    return `# Hoodstrut Benchmark Report\n\n_Generated ${generatedAt}_\n\nNo results found.\n\n---\n${FOOTER}\n`;
  }

  const model = buildReportModel(results, persistedAnalysis);
  const { analysis, aggregate, profiles, tasks, matrix, rankedRuns } = model;
  const lines: string[] = ['# Hoodstrut Benchmark Report', ''];

  lines.push(`> **${decisionLabel(analysis)}.** ${analysis.decision.reason}`);
  lines.push('');
  lines.push(
    `_Generated ${generatedAt} · ${profiles.length} profile(s) × ${tasks.length} task(s) × `
    + `${analysis.repetitions} repetition(s) · methodology: \`${analysis.methodology}\`_`
  );
  lines.push('');
  lines.push('Correctness is ranked first. Cost per verified pass breaks exact correctness ties; duration per verified pass breaks remaining ties. Incomplete profiles are ineligible.');
  lines.push('');

  lines.push('## Summary', '');
  lines.push('| Metric | Value |', '|---|---:|');
  lines.push(`| Expected samples | ${aggregate.expectedRuns} |`);
  lines.push(`| Valid samples | ${aggregate.validRuns} |`);
  lines.push(`| Passed | ${aggregate.successfulRuns} |`);
  lines.push(`| Failed | ${aggregate.failedRuns} |`);
  lines.push(`| Timed out | ${aggregate.timedOutRuns} |`);
  lines.push(`| Errored | ${aggregate.erroredRuns} |`);
  lines.push(`| Missing | ${aggregate.missingRuns} |`);
  lines.push(`| Total cost | ${formatCost(aggregate.totalCost)} |`);
  lines.push(`| Total duration | ${formatDuration(aggregate.totalDuration)} |`);
  lines.push('');

  lines.push('## Results Matrix', '');
  lines.push('Each cell is `passes/expected · mean cost · mean duration`. `error` and `missing` counts make incomplete samples explicit.');
  lines.push('');
  lines.push(`| Task | ${profiles.map(profile => profile.name).join(' | ')} |`);
  lines.push(`|:---|${profiles.map(() => '---:').join('|')}|`);
  for (const task of tasks) {
    const row = matrix.get(task.id)!;
    const cells = profiles.map(profile => {
      const cell = row.get(profile.name)!;
      const cost = cell.mean_cost_usd === null ? '-' : formatCost(cell.mean_cost_usd);
      const duration = cell.mean_duration_seconds === null ? '-' : formatDuration(cell.mean_duration_seconds);
      const problems = [
        cell.errored > 0 ? `${cell.errored} error` : '',
        cell.missing > 0 ? `${cell.missing} missing` : '',
      ].filter(Boolean).join(', ');
      const value = `${cell.passed}/${cell.expected_samples} · ${cost} · ${duration}${problems ? ` · ${problems}` : ''}`;
      return cell.isBestInRow ? `**${value}**` : value;
    });
    lines.push(`| **${task.id}** | ${cells.join(' | ')} |`);
  }
  lines.push('');

  lines.push('## Profile Ranking', '');
  lines.push('| Rank | Profile | Coverage | Passed | Success (95% CI) | Cost / pass | Time / pass | Cost SD | Status |');
  lines.push('|---:|---|---:|---:|---:|---:|---:|---:|---|');
  for (const profile of profiles) {
    const rank = profile.rank ?? '-';
    const success = profile.success_rate === null
      ? '-'
      : `${formatPercent(profile.success_rate)} (${formatInterval(profile.success_confidence_interval_95, true)})`;
    lines.push(
      `| ${rank} | \`${profile.name}\` | ${profile.valid_samples}/${profile.expected_samples} | `
      + `${profile.passed} | ${success} | `
      + `${profile.cost_per_pass_usd === null ? '-' : formatCost(profile.cost_per_pass_usd)} | `
      + `${profile.duration_per_pass_seconds === null ? '-' : formatDuration(profile.duration_per_pass_seconds)} | `
      + `${profile.cost.standard_deviation === null ? 'unavailable' : formatCost(profile.cost.standard_deviation)} | `
      + `${profile.eligible ? 'eligible' : 'ineligible'} |`
    );
  }
  lines.push('');

  lines.push('## Efficiency Statistics', '');
  lines.push('Efficiency statistics include every valid attempt. They affect ranking only after exact correctness ties.');
  lines.push('');
  lines.push('| Profile | Cost mean (95% CI) | Cost variance | Duration mean (95% CI) | Duration variance |');
  lines.push('|---|---:|---:|---:|---:|');
  for (const profile of profiles) {
    const costMean = profile.cost.mean === null ? '-' : formatCost(profile.cost.mean);
    const durationMean = profile.duration.mean === null ? '-' : formatDuration(profile.duration.mean);
    lines.push(
      `| \`${profile.name}\` | ${costMean} (${formatContinuousInterval(profile.cost.confidence_interval_95, formatCost)}) | `
      + `${profile.cost.variance === null ? 'unavailable' : profile.cost.variance.toFixed(6)} | `
      + `${durationMean} (${formatContinuousInterval(profile.duration.confidence_interval_95, formatDuration)}) | `
      + `${profile.duration.variance === null ? 'unavailable' : profile.duration.variance.toFixed(2)} |`
    );
  }
  lines.push('');

  if (analysis.repetitions < 2) {
    lines.push('> Variance and mean confidence intervals require at least two repetitions. This result is exploratory.');
    lines.push('');
  }

  lines.push('## Individual Runs', '');
  lines.push('| Task | Profile | Repetition | Status | Cost | Time |');
  lines.push('|---|---|---:|---|---:|---:|');
  for (const run of rankedRuns) {
    lines.push(
      `| ${run.taskId} | \`${run.profile}\` | ${run.repetition} | ${run.status} | `
      + `${run.cost === null ? '-' : formatCost(run.cost)} | `
      + `${run.duration === null ? '-' : formatDuration(run.duration)} |`
    );
  }
  lines.push('', '---', FOOTER);
  return lines.join('\n');
}
